apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "central-directory.name" . }}-config
data:
  LISTEN_ADDRESS: '0.0.0.0'
  LISTEN_PORT: "3000"

  DATABASE_DIALECT: {{ .Values.database.dialect | quote}}
  DATABASE_HOST: {{ (printf "%s-%s" "pi32" .Values.database.host) | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote}}
  DATABASE_USER: {{ .Values.database.user | quote}}
  DATABASE_PASSWORD: {{ .Values.database.password | quote}}
  DATABASE_SCHEMA: {{ .Values.database.schema | quote}}
#  CLIENT_KEY_FILENAME: {{ .Values.secretsMountPoint }}/clientkey.pem
#  CLIENT_CERT_FILENAME: {{ .Values.secretsMountPoint }}/clientcert.pem
#  CA_CERT_FILENAME: {{ .Values.secretsMountPoint }}/pathfindercert.pem

  REJECT_UNAUTHORIZED: {{ .Values.rejectUnauthorized | quote}}

  PATHFINDER_HOST: {{ .Values.pathfinder.host | quote}}
  PATHFINDER_PORT: {{ .Values.pathfinder.port | quote}}
  QUERY_TIMEOUT_MS: {{ .Values.pathfinder.queryTimeoutMs | quote}}
