apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "central-directory-init.fullname" . }}
  labels:
    app: {{ template "central-directory-init.name" . }}
    chart: {{ template "central-directory-init.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "central-directory-init.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "central-directory-init.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLEDG_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
          livenessProbe:
            exec:
              command:
                - ls
          readinessProbe:
            exec:
              command:
                - ls
      imagePullSecrets:
        - name: regcred 

